/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regression;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.NumberFormatter;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.function.Function2D;
import org.jfree.data.function.LineFunction2D;
import org.jfree.data.general.DatasetUtilities;
import org.jfree.data.statistics.Regression;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import style.FButton;
import style.FTable;

/**
 *
 * @author Fikri-Falndi
 */
public class _calculation extends javax.swing.JFrame {

    /**
     * Creates new form _calculation
     */
    
    public _calculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane6 = new javax.swing.JTabbedPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new FButton("Hitung");
        jButton2 = new FButton("Reset");
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Analysis");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(805, 405));
        setResizable(false);

        jTabbedPane6.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTabbedPane6.setPreferredSize(new java.awt.Dimension(805, 385));

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(775, 525));
        jPanel2.setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Model", "Beta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }
        jTable1.getColumnModel().getColumn(0).setCellRenderer(new FTable());
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new FTable());
        jTable1.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 16));

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 760, 127);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Nilai Beta");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(345, 10, 90, 22);

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 41, 800, 1);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(42, 42, 42));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("Analisis : \n");
        jTextArea3.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(jTextArea3);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(10, 200, 760, 310);

        jScrollPane7.setViewportView(jPanel2);

        jTabbedPane6.addTab("   Nilai Beta    ", jScrollPane7);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Model", "Sum of Squares", "df", "Mean Square", "F Hitung", "F Table"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setEnabled(false);
        jTable2.setGridColor(new java.awt.Color(204, 204, 204));
        jTable2.setRowHeight(25);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
        }
        jTable2.getColumnModel().getColumn(0).setCellRenderer(new FTable());
        jTable2.getColumnModel().getColumn(1).setCellRenderer(new FTable());
        jTable2.getColumnModel().getColumn(2).setCellRenderer(new FTable());
        jTable2.getColumnModel().getColumn(3).setCellRenderer(new FTable());
        jTable2.getColumnModel().getColumn(4).setCellRenderer(new FTable());
        jTable2.getColumnModel().getColumn(5).setCellRenderer(new FTable());
        jTable2.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 16));

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 770, 108);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Uji Anova");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(350, 10, 90, 22);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(42, 42, 42));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(3);
        jTextArea1.setText("Analisis :");
        jScrollPane4.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(10, 180, 770, 130);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setOpaque(true);
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 41, 800, 1);

        jTabbedPane6.addTab("    Uji Anova    ", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "R", "R Square", "Adjusted R Square", "Std. Error of the Estimate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setEnabled(false);
        jTable3.setGridColor(new java.awt.Color(204, 204, 204));
        jTable3.setRowHeight(25);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(3).setResizable(false);
        }
        jTable3.getColumnModel().getColumn(0).setCellRenderer(new FTable());
        jTable3.getColumnModel().getColumn(1).setCellRenderer(new FTable());
        jTable3.getColumnModel().getColumn(2).setCellRenderer(new FTable());
        jTable3.getColumnModel().getColumn(3).setCellRenderer(new FTable());
        jTable3.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 16));

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(10, 60, 770, 58);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Uji Koefisien");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(335, 10, 120, 22);

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setOpaque(true);
        jPanel4.add(jLabel8);
        jLabel8.setBounds(0, 41, 800, 1);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(42, 42, 42));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(3);
        jTextArea2.setText("Analisis :");
        jTextArea2.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane5);
        jScrollPane5.setBounds(10, 130, 770, 170);

        jTabbedPane6.addTab("    Uji Koef     ", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Nilai SBI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 60, 70, 27);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nilai Laju Inflasi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 100, 120, 27);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Nilai Kurs Dollar");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 140, 120, 27);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(160, 60, 190, 27);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(160, 100, 190, 27);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(160, 140, 190, 27);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel5.setLayout(null);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(16, 27, 128, 35);

        jButton2.setText("Reset");
        jPanel5.add(jButton2);
        jButton2.setBounds(16, 70, 128, 32);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(360, 52, 160, 117);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Prediksi Nilai IHSG");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 10, 170, 22);

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 41, 800, 1);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(42, 42, 42));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(3);
        jTextArea4.setText("Analisis :");
        jTextArea4.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane8.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane8);
        jScrollPane8.setBounds(10, 180, 770, 150);

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(42, 42, 42));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea5.setRows(3);
        jTextArea5.setText("Masukkan data terakhir dari masing -\nmasing inputan nilai disamping yang\ndapat diperoleh di :\nNilai SBI : www.gps.go.id\nNilai Laju Inflasi : www.bi.go.id\nNilai Kurs Dollar : www.bi.go.id");
        jTextArea5.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane9.setViewportView(jTextArea5);

        jPanel1.add(jScrollPane9);
        jScrollPane9.setBounds(530, 60, 250, 110);

        jTabbedPane6.addTab("    Prediksi     ", jPanel1);

        getContentPane().add(jTabbedPane6, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        number(evt, jTextField1);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        number(evt, jTextField2);
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        number(evt, jTextField3);
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            DecimalFormat df = new DecimalFormat("#.00#");

            double IHSG = constant + ((sbi * Double.parseDouble(jTextField1.getText()))
                    + (inflasi * Double.parseDouble(jTextField2.getText()))
                    + (kurs * Double.parseDouble(jTextField3.getText())));
            
            _dataImport di = new _dataImport();
            int lastIndex = di.jTable1.getModel().getRowCount();
            int month = 0;
            
            String [][]bulan = {
                                {"1","Januari"},{"2","Februari"},{"3","Maret"},
                                {"4","April"},{"5","Mei"},{"6","Juni"},
                                {"7","Juli"},{"8","Agustus"},{"9","September"},
                                {"10","Oktober"},{"11","November"},{"12","Desember"}
                                };
            
            System.out.println(lastMonth);
            int i1 = 0, indeks = 0;
            for(String[] ll : bulan){
                int i2 = 0;
                for(String l2:ll){
                    if(bulan[i1][i2].equals(lastMonth)){
                        System.out.println(i1 + " " + i2);
                        indeks = i1;
                    }
                    i2++;
                }
                i1++;
            }
            
            System.out.println(indeks);
            
            String analisis = "Analisis :\n"
                    + "Prediksi Nilai IHSG = " + df.format(IHSG) + "\n"
                    + "Prediksi Nilai IHSG (" + df.format(IHSG) + ") " + (IHSG > lastIHSG ? ">" : "<") + " Nilai IHSG Record Terakhir (" + df.format(lastIHSG) + ").\n"
                    + "\nKesimpulan :\n"
                    + "Nilai IHSG mengalami " + (IHSG > lastIHSG ? "kenaikan" : "penurunan") + ", maka Investasi " + (IHSG > lastIHSG ? "baik" : "sebaiknya tidak") + " dilakukan untuk bulan " + bulan[indeks+1][1] + "\n2016.";
            jTextArea4.setText(analisis);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Harap isi semua kolom!", "Warning", JOptionPane.OK_OPTION);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void number(java.awt.event.KeyEvent evt, JTextField text){
        double c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_PERIOD)
                || (c == KeyEvent.VK_MINUS)) || text.getText().length() >= 20) {
            getToolkit().beep();
            evt.consume();
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _calculation().setVisible(true);
            }
        });
    }

    public double constant, sbi, inflasi, kurs, lastIHSG;
    public String lastMonth;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTabbedPane jTabbedPane6;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    public javax.swing.JTable jTable3;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
